### ISSUE TITLE
Heap Simulator simulation mode says that block coalesces when they do not

### ISSUE THREAD

**Issue by andrewhu-uw** [sarangjo/sarangjo.github.io#1]
For example, try the following:

 - malloc(64)
 - malloc(32)
 - free(8)

Simulation mode will say "block coalesced" even though it obviously has not

**Comment by sarangjo** [comment]
Hi there, thanks for your feedback! The code right now always prints out "block coalesced" (that is intended behavior), but I do agree that it would make more sense to only print that out when a block is actually coalesced.

**Comment by andrewhu-uw** [comment]
Hello Sarang, I'm managing CSE 351's heap lab this quarter, is there any chance I could get the source code for the simulator? I assume it's hosted in a private repo.

**Comment by andrewhu-uw** [comment]
Issue has been fixed on the heap simulator repo, and should be available soon
